# mkdocs serve

site_name: IBM Watson IoT Platform
site_url: https://ibm-watson-iot.github.io/iot-python

repo_name: GitHub
repo_url: https://github.com/ibm-watson-iot/iot-python
edit_uri: blob/master/docs/

nav:
  - 'Python SDK': index.md
  - 'Common Topics':
    - 'Basic Concepts': concepts.md
    - 'MQTT Primer': mqtt.md
    - 'Custom Message Formats': custommsg.md
    - 'Exceptions': exceptions.md
  - 'Application Development':
    - 'Application SDK': application/index.md
    - 'Configuration': application/config.md
    - 'Device Commands': application/mqtt/commands.md
    - 'Device Events': application/mqtt/events.md
    - 'Device Status Updates': application/mqtt/status.md
    - 'Registry - Types': application/api/registry/types.md
    - 'Registry - Devices': application/api/registry/devices.md
    - 'Registry - Diagnostics': application/api/registry/diag.md
    - 'Device Management': application/api/mgmt.md
    - 'Service Bindings': application/api/bindings.md
    - 'Data Store Connectors': application/api/dsc.md
    - 'Last Event Cache': application/api/lec.md
    - 'Service Status': application/api/status.md
    - 'Usage Reports': application/api/usage.md
  - 'Device Development':
    - 'Device SDK': device/index.md
    - 'Configuration': device/config.md
    - 'Managed Devices': device/managed.md
  - 'Gateway Development':
    - 'Gateway SDK': gateway/index.md
    - 'Configuration': gateway/config.md
    - 'Managed Gateways': gateway/managed.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# Note
# Abstract
# Info
# Tip
# Success
# Question
# Warning
# Failure
# Danger
# Bug
# Example
# Quote
