name: Build Documentation
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          python -m pip install -q mkdocs
          mkdocs build --verbose --clean --strict

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        # if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: site
